# Maximum number of fragments in a final assembly
# limited by Gibson diminishing efficiency with fragment count
fragments-max-count: 6

# Minimum homology length between fragments
fragments-min-junction-length: 15

# Maximum homology length between fragments
fragments-max-junction-length: 120

# Maximum allowable hairpin melting temperature (celcius)
fragments-max-junction-hairpin: 47.0

# Cost per Gibson assembly reaction
# $649.00 / 50
# from https://www.neb.com/products/e2611-gibson-assembly-master-mix#Product%20Information
gibson-assembly-cost: 12.98

# Cost per bp of PCR primer. based on IDT prices
pcr-bp-cost: 0.6

# Cost per PCR reaction
# $54.75 / 200
# estimated from manual at https://www.thermofisher.com/order/catalog/product/18067017
pcr-rxn-cost: 0.27

# Minimum length of a PCR fragment
pcr-min-length: 60

# Max primer3 pair penalty score
pcr-primer-max-pair-penalty: 30.0

# Max embedded length. The most bp to include upstream of a annealing portion
# of a primer to create or extend a junction with another part
pcr-primer-max-embed-length: 20

# Max off-target primer binding site Tm, above which a PCR is abandoned
pcr-primer-max-offtarget-tm: 55.0

# The length of PCR buffer. The length of the ranges to allow Primer3 to
# choose primers in if neighbors are both synthetic. The larger this number,
# the "better" the primers may be, but at the cost of a more expensive plasmid
# (more synthesis)
pcr-buffer-length: 20

# Minimum length of a synthesized building fragment
synthetic-min-length: 125

# Maximum length of a synthesized building fragment
synthetic-max-length: 3000

# Cost of synthesis (step-function)
# the key here is the upper limit on the synthesis to that range
# so 500: is synthesis from whatever length is less than that key up to it
synthetic-fragment-cost:
  # IDT: gBlocks: https://www.idtdna.com/pages/products/genes-and-gene-fragments/gblocks-gene-fragments
  250:
    fixed: true
    cost: 89.0

  500:
    fixed: true
    cost: 89.0

  750:
    fixed: true
    cost: 129.0

  1000:
    fixed: true
    cost: 149.0

  1250:
    fixed: true
    cost: 209.0

  1500:
    fixed: true
    cost: 249.0

  1750:
    fixed: true
    cost: 289.0

  2000:
    fixed: true
    cost: 329.0

  2250:
    fixed: true
    cost: 399.0

  2500:
    fixed: true
    cost: 449.0

  2750:
    fixed: true
    cost: 499.0

  3000:
    fixed: true
    cost: 549.0

# Cost of synthesis and delivery in a plasmid
# IDT: Gene synthesis: https://www.idtdna.com/pages/products/genes-and-gene-fragments/custom-gene-synthesis
synthetic-plasmid-cost:
  500:
    fixed: true
    cost: 160

  3000:
    fixed: false
    cost: 0.35

  30000:
    fixed: false
    cost: 0.6

# cost of a single addgene plasmid
addgene-cost: 65.0

# cost of a single igem part
#
# "The iGEM Labs program provides members with program benefits such as
# access to the Registry of Standard Biological parts. As a member of an
# iGEM lab, you would receive the annual DNA distribution and up to
# 75 individual part requests. The current cost of joining the iGEM Labs
# program is $500 per subscription year."
igem-cost: 0.0

# 55 for academic customers, 65 for corporate
dnasu-cost: 55.0
